CRITICAL - 2021-04-23 10:59:44 --> Class 'App\Controllers\cliente\LoginModel' not found
#0 C:\xampp\htdocs\lexsoft\app\Controllers\cliente\Plantilla.php(9): App\Controllers\cliente\Plantilla->vistaDashboarPlantilla(Array, 'plantilla/nueva...')
#1 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(936): App\Controllers\cliente\Plantilla->index()
#2 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\cliente\Plantilla))
#3 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\lexsoft\public\index.php(44): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-04-23 11:30:50 --> Trying to access array offset on value of type null
#0 C:\xampp\htdocs\lexsoft\app\Views\cliente\usuarioCliente\editCliente.php(19): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to acces...', 'C:\\xampp\\htdocs...', 19, Array)
#1 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\View\View.php(220): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\View\View.php(222): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Common.php(1217): CodeIgniter\View\View->render('cliente/usuario...', Array, true)
#4 C:\xampp\htdocs\lexsoft\app\Controllers\cliente\UserCliente.php(136): view('cliente/usuario...', Array)
#5 C:\xampp\htdocs\lexsoft\app\Controllers\cliente\UserCliente.php(89): App\Controllers\cliente\UserCliente->vistaDashboarCliente('usuarioCliente/...', Array)
#6 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(936): App\Controllers\cliente\UserCliente->edit_cliente('dist', 'img', 'user1-128x128.j...')
#7 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\cliente\UserCliente))
#8 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\lexsoft\public\index.php(44): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2021-04-23 11:30:50 --> Trying to access array offset on value of type null
#0 C:\xampp\htdocs\lexsoft\app\Views\cliente\usuarioCliente\editCliente.php(19): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to acces...', 'C:\\xampp\\htdocs...', 19, Array)
#1 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\View\View.php(220): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\View\View.php(222): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Common.php(1217): CodeIgniter\View\View->render('cliente/usuario...', Array, true)
#4 C:\xampp\htdocs\lexsoft\app\Controllers\cliente\UserCliente.php(136): view('cliente/usuario...', Array)
#5 C:\xampp\htdocs\lexsoft\app\Controllers\cliente\UserCliente.php(89): App\Controllers\cliente\UserCliente->vistaDashboarCliente('usuarioCliente/...', Array)
#6 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(936): App\Controllers\cliente\UserCliente->edit_cliente('dist', 'img', 'user8-128x128.j...')
#7 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\cliente\UserCliente))
#8 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\lexsoft\public\index.php(44): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2021-04-23 11:30:50 --> Trying to access array offset on value of type null
#0 C:\xampp\htdocs\lexsoft\app\Views\cliente\usuarioCliente\editCliente.php(19): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to acces...', 'C:\\xampp\\htdocs...', 19, Array)
#1 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\View\View.php(220): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\View\View.php(222): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Common.php(1217): CodeIgniter\View\View->render('cliente/usuario...', Array, true)
#4 C:\xampp\htdocs\lexsoft\app\Controllers\cliente\UserCliente.php(136): view('cliente/usuario...', Array)
#5 C:\xampp\htdocs\lexsoft\app\Controllers\cliente\UserCliente.php(89): App\Controllers\cliente\UserCliente->vistaDashboarCliente('usuarioCliente/...', Array)
#6 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(936): App\Controllers\cliente\UserCliente->edit_cliente('dist', 'img', 'user3-128x128.j...')
#7 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\cliente\UserCliente))
#8 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\lexsoft\public\index.php(44): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2021-04-23 11:46:39 --> syntax error, unexpected '}', expecting ';' or ','
#0 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Autoloader\Autoloader.php(265): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\xampp\\htdocs...')
#1 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Autoloader\Autoloader.php(228): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(893): class_exists('\\App\\Controller...', true)
#5 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(417): CodeIgniter\CodeIgniter->startController()
#6 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\lexsoft\public\index.php(44): CodeIgniter\CodeIgniter->run()
#8 {main}
ERROR - 2021-04-23 11:50:50 --> mysqli_sql_exception: Column 'plantilla' cannot be null in C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:314
Stack trace:
#0 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(314): mysqli->query('INSERT INTO `le...')
#1 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Database\BaseConnection.php(713): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `le...')
#2 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Database\BaseConnection.php(641): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `le...')
#3 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2263): CodeIgniter\Database\BaseConnection->query('INSERT INTO `le...', Array, false)
#4 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Model.php(278): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\BaseModel.php(758): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Model.php(705): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\lexsoft\app\Controllers\cliente\Plantilla.php(29): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(936): App\Controllers\cliente\Plantilla->insert_plantilla()
#9 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\cliente\Plantilla))
#10 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\lexsoft\public\index.php(44): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2021-04-23 11:50:50 --> Column 'plantilla' cannot be null
#0 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(314): mysqli->query('INSERT INTO `le...')
#1 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Database\BaseConnection.php(713): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `le...')
#2 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Database\BaseConnection.php(641): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `le...')
#3 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2263): CodeIgniter\Database\BaseConnection->query('INSERT INTO `le...', Array, false)
#4 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Model.php(278): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\BaseModel.php(758): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Model.php(705): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\lexsoft\app\Controllers\cliente\Plantilla.php(29): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(936): App\Controllers\cliente\Plantilla->insert_plantilla()
#9 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\cliente\Plantilla))
#10 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\lexsoft\public\index.php(44): CodeIgniter\CodeIgniter->run()
#12 {main}
ERROR - 2021-04-23 11:51:26 --> mysqli_sql_exception: Column 'plantilla' cannot be null in C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:314
Stack trace:
#0 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(314): mysqli->query('INSERT INTO `le...')
#1 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Database\BaseConnection.php(713): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `le...')
#2 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Database\BaseConnection.php(641): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `le...')
#3 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2263): CodeIgniter\Database\BaseConnection->query('INSERT INTO `le...', Array, false)
#4 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Model.php(278): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\BaseModel.php(758): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Model.php(705): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\lexsoft\app\Controllers\cliente\Plantilla.php(29): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(936): App\Controllers\cliente\Plantilla->insert_plantilla()
#9 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\cliente\Plantilla))
#10 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\lexsoft\public\index.php(44): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2021-04-23 11:51:26 --> Column 'plantilla' cannot be null
#0 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(314): mysqli->query('INSERT INTO `le...')
#1 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Database\BaseConnection.php(713): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `le...')
#2 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Database\BaseConnection.php(641): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `le...')
#3 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2263): CodeIgniter\Database\BaseConnection->query('INSERT INTO `le...', Array, false)
#4 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Model.php(278): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\BaseModel.php(758): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Model.php(705): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\lexsoft\app\Controllers\cliente\Plantilla.php(29): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(936): App\Controllers\cliente\Plantilla->insert_plantilla()
#9 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\cliente\Plantilla))
#10 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\lexsoft\public\index.php(44): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2021-04-23 13:25:03 --> Illegal string offset 'data'
#0 C:\xampp\htdocs\lexsoft\app\Controllers\cliente\Dashboard.php(22): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Illegal string ...', 'C:\\xampp\\htdocs...', 22, Array)
#1 C:\xampp\htdocs\lexsoft\app\Controllers\cliente\Dashboard.php(13): App\Controllers\cliente\Dashboard->vistaDashboarCliente('dashboardClient...', Array)
#2 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(936): App\Controllers\cliente\Dashboard->index()
#3 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\cliente\Dashboard))
#4 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\lexsoft\public\index.php(44): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2021-04-23 13:50:02 --> Array to string conversion
#0 C:\xampp\htdocs\lexsoft\app\Controllers\cliente\Plantilla.php(56): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Array to string...', 'C:\\xampp\\htdocs...', 56, Array)
#1 C:\xampp\htdocs\lexsoft\app\Controllers\cliente\Plantilla.php(48): App\Controllers\cliente\Plantilla->vistaDashboarPlantilla('usuarioCliente/...', Array)
#2 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(936): App\Controllers\cliente\Plantilla->listar_plantilla()
#3 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\cliente\Plantilla))
#4 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\lexsoft\public\index.php(44): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2021-04-23 13:54:11 --> Trying to access array offset on value of type null
#0 C:\xampp\htdocs\lexsoft\app\Views\cliente\usuarioCliente\editCliente.php(19): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to acces...', 'C:\\xampp\\htdocs...', 19, Array)
#1 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\View\View.php(220): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\View\View.php(222): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Common.php(1217): CodeIgniter\View\View->render('cliente/usuario...', Array, true)
#4 C:\xampp\htdocs\lexsoft\app\Controllers\cliente\UserCliente.php(136): view('cliente/usuario...', Array)
#5 C:\xampp\htdocs\lexsoft\app\Controllers\cliente\UserCliente.php(89): App\Controllers\cliente\UserCliente->vistaDashboarCliente('usuarioCliente/...', Array)
#6 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(936): App\Controllers\cliente\UserCliente->edit_cliente('dist', 'img', 'user1-128x128.j...')
#7 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\cliente\UserCliente))
#8 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\lexsoft\public\index.php(44): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2021-04-23 13:54:11 --> Trying to access array offset on value of type null
#0 C:\xampp\htdocs\lexsoft\app\Views\cliente\usuarioCliente\editCliente.php(19): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to acces...', 'C:\\xampp\\htdocs...', 19, Array)
#1 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\View\View.php(220): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\View\View.php(222): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Common.php(1217): CodeIgniter\View\View->render('cliente/usuario...', Array, true)
#4 C:\xampp\htdocs\lexsoft\app\Controllers\cliente\UserCliente.php(136): view('cliente/usuario...', Array)
#5 C:\xampp\htdocs\lexsoft\app\Controllers\cliente\UserCliente.php(89): App\Controllers\cliente\UserCliente->vistaDashboarCliente('usuarioCliente/...', Array)
#6 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(936): App\Controllers\cliente\UserCliente->edit_cliente('dist', 'img', 'user8-128x128.j...')
#7 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\cliente\UserCliente))
#8 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\lexsoft\public\index.php(44): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2021-04-23 13:54:11 --> Trying to access array offset on value of type null
#0 C:\xampp\htdocs\lexsoft\app\Views\cliente\usuarioCliente\editCliente.php(19): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to acces...', 'C:\\xampp\\htdocs...', 19, Array)
#1 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\View\View.php(220): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\View\View.php(222): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Common.php(1217): CodeIgniter\View\View->render('cliente/usuario...', Array, true)
#4 C:\xampp\htdocs\lexsoft\app\Controllers\cliente\UserCliente.php(136): view('cliente/usuario...', Array)
#5 C:\xampp\htdocs\lexsoft\app\Controllers\cliente\UserCliente.php(89): App\Controllers\cliente\UserCliente->vistaDashboarCliente('usuarioCliente/...', Array)
#6 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(936): App\Controllers\cliente\UserCliente->edit_cliente('dist', 'img', 'user3-128x128.j...')
#7 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\cliente\UserCliente))
#8 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\lexsoft\public\index.php(44): CodeIgniter\CodeIgniter->run()
#10 {main}
ERROR - 2021-04-23 13:57:00 --> mysqli_sql_exception: Column 'primer_nombre' cannot be null in C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:314
Stack trace:
#0 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(314): mysqli->query('INSERT INTO `le...')
#1 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Database\BaseConnection.php(713): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `le...')
#2 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Database\BaseConnection.php(641): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `le...')
#3 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2263): CodeIgniter\Database\BaseConnection->query('INSERT INTO `le...', Array, false)
#4 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Model.php(278): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\BaseModel.php(758): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Model.php(705): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\lexsoft\app\Controllers\cliente\UserCliente.php(50): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(936): App\Controllers\cliente\UserCliente->insert_user()
#9 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\cliente\UserCliente))
#10 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\lexsoft\public\index.php(44): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2021-04-23 13:57:00 --> Column 'primer_nombre' cannot be null
#0 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(314): mysqli->query('INSERT INTO `le...')
#1 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Database\BaseConnection.php(713): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `le...')
#2 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Database\BaseConnection.php(641): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `le...')
#3 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2263): CodeIgniter\Database\BaseConnection->query('INSERT INTO `le...', Array, false)
#4 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Model.php(278): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\BaseModel.php(758): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Model.php(705): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\lexsoft\app\Controllers\cliente\UserCliente.php(50): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(936): App\Controllers\cliente\UserCliente->insert_user()
#9 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\cliente\UserCliente))
#10 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\lexsoft\public\index.php(44): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2021-04-23 14:00:17 --> Trying to access array offset on value of type null
#0 C:\xampp\htdocs\lexsoft\app\Views\admin\usuario\editUser.php(19): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to acces...', 'C:\\xampp\\htdocs...', 19, Array)
#1 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\View\View.php(220): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\View\View.php(222): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Common.php(1217): CodeIgniter\View\View->render('admin/usuario/e...', Array, true)
#4 C:\xampp\htdocs\lexsoft\app\Controllers\admin\User.php(135): view('admin/usuario/e...', Array)
#5 C:\xampp\htdocs\lexsoft\app\Controllers\admin\User.php(88): App\Controllers\admin\User->vistaDashboarAdmin('usuario/editUse...', Array)
#6 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(936): App\Controllers\admin\User->editUser('dist', 'img', 'user1-128x128.j...')
#7 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\admin\User))
#8 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\lexsoft\public\index.php(44): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2021-04-23 14:00:17 --> Trying to access array offset on value of type null
#0 C:\xampp\htdocs\lexsoft\app\Views\admin\usuario\editUser.php(19): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to acces...', 'C:\\xampp\\htdocs...', 19, Array)
#1 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\View\View.php(220): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\View\View.php(222): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Common.php(1217): CodeIgniter\View\View->render('admin/usuario/e...', Array, true)
#4 C:\xampp\htdocs\lexsoft\app\Controllers\admin\User.php(135): view('admin/usuario/e...', Array)
#5 C:\xampp\htdocs\lexsoft\app\Controllers\admin\User.php(88): App\Controllers\admin\User->vistaDashboarAdmin('usuario/editUse...', Array)
#6 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(936): App\Controllers\admin\User->editUser('dist', 'img', 'user8-128x128.j...')
#7 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\admin\User))
#8 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\lexsoft\public\index.php(44): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2021-04-23 14:00:17 --> Trying to access array offset on value of type null
#0 C:\xampp\htdocs\lexsoft\app\Views\admin\usuario\editUser.php(19): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to acces...', 'C:\\xampp\\htdocs...', 19, Array)
#1 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\View\View.php(220): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\View\View.php(222): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Common.php(1217): CodeIgniter\View\View->render('admin/usuario/e...', Array, true)
#4 C:\xampp\htdocs\lexsoft\app\Controllers\admin\User.php(135): view('admin/usuario/e...', Array)
#5 C:\xampp\htdocs\lexsoft\app\Controllers\admin\User.php(88): App\Controllers\admin\User->vistaDashboarAdmin('usuario/editUse...', Array)
#6 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(936): App\Controllers\admin\User->editUser('dist', 'img', 'user3-128x128.j...')
#7 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\admin\User))
#8 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\lexsoft\public\index.php(44): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2021-04-23 14:35:53 --> Trying to access array offset on value of type null
#0 C:\xampp\htdocs\lexsoft\app\Views\cliente\usuarioCliente\editCliente.php(19): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to acces...', 'C:\\xampp\\htdocs...', 19, Array)
#1 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\View\View.php(220): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\View\View.php(222): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Common.php(1217): CodeIgniter\View\View->render('cliente/usuario...', Array, true)
#4 C:\xampp\htdocs\lexsoft\app\Controllers\cliente\UserCliente.php(136): view('cliente/usuario...', Array)
#5 C:\xampp\htdocs\lexsoft\app\Controllers\cliente\UserCliente.php(89): App\Controllers\cliente\UserCliente->vistaDashboarCliente('usuarioCliente/...', Array)
#6 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(936): App\Controllers\cliente\UserCliente->edit_cliente('dist', 'img', 'user1-128x128.j...')
#7 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\cliente\UserCliente))
#8 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\lexsoft\public\index.php(44): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2021-04-23 14:35:53 --> Trying to access array offset on value of type null
#0 C:\xampp\htdocs\lexsoft\app\Views\cliente\usuarioCliente\editCliente.php(19): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to acces...', 'C:\\xampp\\htdocs...', 19, Array)
#1 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\View\View.php(220): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\View\View.php(222): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Common.php(1217): CodeIgniter\View\View->render('cliente/usuario...', Array, true)
#4 C:\xampp\htdocs\lexsoft\app\Controllers\cliente\UserCliente.php(136): view('cliente/usuario...', Array)
#5 C:\xampp\htdocs\lexsoft\app\Controllers\cliente\UserCliente.php(89): App\Controllers\cliente\UserCliente->vistaDashboarCliente('usuarioCliente/...', Array)
#6 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(936): App\Controllers\cliente\UserCliente->edit_cliente('dist', 'img', 'user8-128x128.j...')
#7 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\cliente\UserCliente))
#8 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\lexsoft\public\index.php(44): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2021-04-23 14:35:53 --> Trying to access array offset on value of type null
#0 C:\xampp\htdocs\lexsoft\app\Views\cliente\usuarioCliente\editCliente.php(19): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to acces...', 'C:\\xampp\\htdocs...', 19, Array)
#1 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\View\View.php(220): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\View\View.php(222): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Common.php(1217): CodeIgniter\View\View->render('cliente/usuario...', Array, true)
#4 C:\xampp\htdocs\lexsoft\app\Controllers\cliente\UserCliente.php(136): view('cliente/usuario...', Array)
#5 C:\xampp\htdocs\lexsoft\app\Controllers\cliente\UserCliente.php(89): App\Controllers\cliente\UserCliente->vistaDashboarCliente('usuarioCliente/...', Array)
#6 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(936): App\Controllers\cliente\UserCliente->edit_cliente('dist', 'img', 'user3-128x128.j...')
#7 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\cliente\UserCliente))
#8 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\lexsoft\public\index.php(44): CodeIgniter\CodeIgniter->run()
#10 {main}
ERROR - 2021-04-23 14:56:11 --> mysqli_sql_exception: Cannot delete or update a parent row: a foreign key constraint fails (`lexsonft_db`.`lexsoft_tb_casos`, CONSTRAINT `lexsoft_tb_casos_ibfk_1` FOREIGN KEY (`id_cliente`) REFERENCES `lexsoft_tb_users` (`id_user`)) in C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:314
Stack trace:
#0 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(314): mysqli->query('DELETE FROM `le...')
#1 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Database\BaseConnection.php(713): CodeIgniter\Database\MySQLi\Connection->execute('DELETE FROM `le...')
#2 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Database\BaseConnection.php(641): CodeIgniter\Database\BaseConnection->simpleQuery('DELETE FROM `le...')
#3 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2864): CodeIgniter\Database\BaseConnection->query('DELETE FROM `le...', Array, false)
#4 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Model.php(422): CodeIgniter\Database\BaseBuilder->delete()
#5 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\BaseModel.php(1009): CodeIgniter\Model->doDelete(Array, false)
#6 C:\xampp\htdocs\lexsoft\app\Controllers\admin\User.php(121): CodeIgniter\BaseModel->delete(Array)
#7 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(936): App\Controllers\admin\User->delete_user('96')
#8 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\admin\User))
#9 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\lexsoft\public\index.php(44): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2021-04-23 14:56:11 --> Cannot delete or update a parent row: a foreign key constraint fails (`lexsonft_db`.`lexsoft_tb_casos`, CONSTRAINT `lexsoft_tb_casos_ibfk_1` FOREIGN KEY (`id_cliente`) REFERENCES `lexsoft_tb_users` (`id_user`))
#0 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(314): mysqli->query('DELETE FROM `le...')
#1 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Database\BaseConnection.php(713): CodeIgniter\Database\MySQLi\Connection->execute('DELETE FROM `le...')
#2 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Database\BaseConnection.php(641): CodeIgniter\Database\BaseConnection->simpleQuery('DELETE FROM `le...')
#3 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2864): CodeIgniter\Database\BaseConnection->query('DELETE FROM `le...', Array, false)
#4 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Model.php(422): CodeIgniter\Database\BaseBuilder->delete()
#5 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\BaseModel.php(1009): CodeIgniter\Model->doDelete(Array, false)
#6 C:\xampp\htdocs\lexsoft\app\Controllers\admin\User.php(121): CodeIgniter\BaseModel->delete(Array)
#7 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(936): App\Controllers\admin\User->delete_user('96')
#8 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\admin\User))
#9 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\lexsoft\public\index.php(44): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2021-04-23 15:40:45 --> Function name must be a string
#0 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\View\View.php(220): include()
#1 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\View\View.php(222): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#2 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Common.php(1217): CodeIgniter\View\View->render('cliente/casos/n...', Array, true)
#3 C:\xampp\htdocs\lexsoft\app\Controllers\cliente\Casos.php(24): view('cliente/casos/n...', Array)
#4 C:\xampp\htdocs\lexsoft\app\Controllers\cliente\Casos.php(19): App\Controllers\cliente\Casos->vistaDashboarCliente('casos/nuevoCaso', Array)
#5 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(936): App\Controllers\cliente\Casos->nuevo_caso()
#6 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\cliente\Casos))
#7 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\lexsoft\public\index.php(44): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-04-23 15:41:28 --> Trying to get property 'id_consultante' of non-object
#0 C:\xampp\htdocs\lexsoft\app\Views\cliente\casos\nuevoCaso.php(25): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to get p...', 'C:\\xampp\\htdocs...', 25, Array)
#1 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\View\View.php(220): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\View\View.php(222): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Common.php(1217): CodeIgniter\View\View->render('cliente/casos/n...', Array, true)
#4 C:\xampp\htdocs\lexsoft\app\Controllers\cliente\Casos.php(24): view('cliente/casos/n...', Array)
#5 C:\xampp\htdocs\lexsoft\app\Controllers\cliente\Casos.php(19): App\Controllers\cliente\Casos->vistaDashboarCliente('casos/nuevoCaso', Array)
#6 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(936): App\Controllers\cliente\Casos->nuevo_caso()
#7 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\cliente\Casos))
#8 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\lexsoft\public\index.php(44): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2021-04-23 15:43:36 --> Undefined index: id_creado
#0 C:\xampp\htdocs\lexsoft\app\Views\cliente\casos\nuevoCaso.php(25): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined index...', 'C:\\xampp\\htdocs...', 25, Array)
#1 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\View\View.php(220): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\View\View.php(222): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Common.php(1217): CodeIgniter\View\View->render('cliente/casos/n...', Array, true)
#4 C:\xampp\htdocs\lexsoft\app\Controllers\cliente\Casos.php(24): view('cliente/casos/n...', Array)
#5 C:\xampp\htdocs\lexsoft\app\Controllers\cliente\Casos.php(19): App\Controllers\cliente\Casos->vistaDashboarCliente('casos/nuevoCaso', Array)
#6 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(936): App\Controllers\cliente\Casos->nuevo_caso()
#7 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\cliente\Casos))
#8 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\lexsoft\public\index.php(44): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2021-04-23 15:43:38 --> Undefined index: id_creado
#0 C:\xampp\htdocs\lexsoft\app\Views\cliente\casos\nuevoCaso.php(25): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined index...', 'C:\\xampp\\htdocs...', 25, Array)
#1 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\View\View.php(220): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\View\View.php(222): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Common.php(1217): CodeIgniter\View\View->render('cliente/casos/n...', Array, true)
#4 C:\xampp\htdocs\lexsoft\app\Controllers\cliente\Casos.php(24): view('cliente/casos/n...', Array)
#5 C:\xampp\htdocs\lexsoft\app\Controllers\cliente\Casos.php(19): App\Controllers\cliente\Casos->vistaDashboarCliente('casos/nuevoCaso', Array)
#6 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(936): App\Controllers\cliente\Casos->nuevo_caso()
#7 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\cliente\Casos))
#8 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\lexsoft\public\index.php(44): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2021-04-23 15:43:40 --> Undefined index: id_creado
#0 C:\xampp\htdocs\lexsoft\app\Views\cliente\casos\nuevoCaso.php(25): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined index...', 'C:\\xampp\\htdocs...', 25, Array)
#1 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\View\View.php(220): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\View\View.php(222): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Common.php(1217): CodeIgniter\View\View->render('cliente/casos/n...', Array, true)
#4 C:\xampp\htdocs\lexsoft\app\Controllers\cliente\Casos.php(24): view('cliente/casos/n...', Array)
#5 C:\xampp\htdocs\lexsoft\app\Controllers\cliente\Casos.php(19): App\Controllers\cliente\Casos->vistaDashboarCliente('casos/nuevoCaso', Array)
#6 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(936): App\Controllers\cliente\Casos->nuevo_caso()
#7 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\cliente\Casos))
#8 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\lexsoft\public\index.php(44): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2021-04-23 15:43:40 --> Undefined index: id_creado
#0 C:\xampp\htdocs\lexsoft\app\Views\cliente\casos\nuevoCaso.php(25): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined index...', 'C:\\xampp\\htdocs...', 25, Array)
#1 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\View\View.php(220): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\View\View.php(222): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Common.php(1217): CodeIgniter\View\View->render('cliente/casos/n...', Array, true)
#4 C:\xampp\htdocs\lexsoft\app\Controllers\cliente\Casos.php(24): view('cliente/casos/n...', Array)
#5 C:\xampp\htdocs\lexsoft\app\Controllers\cliente\Casos.php(19): App\Controllers\cliente\Casos->vistaDashboarCliente('casos/nuevoCaso', Array)
#6 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(936): App\Controllers\cliente\Casos->nuevo_caso()
#7 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\cliente\Casos))
#8 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\lexsoft\public\index.php(44): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2021-04-23 15:43:40 --> Undefined index: id_creado
#0 C:\xampp\htdocs\lexsoft\app\Views\cliente\casos\nuevoCaso.php(25): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined index...', 'C:\\xampp\\htdocs...', 25, Array)
#1 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\View\View.php(220): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\View\View.php(222): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Common.php(1217): CodeIgniter\View\View->render('cliente/casos/n...', Array, true)
#4 C:\xampp\htdocs\lexsoft\app\Controllers\cliente\Casos.php(24): view('cliente/casos/n...', Array)
#5 C:\xampp\htdocs\lexsoft\app\Controllers\cliente\Casos.php(19): App\Controllers\cliente\Casos->vistaDashboarCliente('casos/nuevoCaso', Array)
#6 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(936): App\Controllers\cliente\Casos->nuevo_caso()
#7 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\cliente\Casos))
#8 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\lexsoft\public\index.php(44): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2021-04-23 15:43:55 --> Trying to get property 'id_creado' of non-object
#0 C:\xampp\htdocs\lexsoft\app\Views\cliente\casos\nuevoCaso.php(25): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to get p...', 'C:\\xampp\\htdocs...', 25, Array)
#1 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\View\View.php(220): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\View\View.php(222): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Common.php(1217): CodeIgniter\View\View->render('cliente/casos/n...', Array, true)
#4 C:\xampp\htdocs\lexsoft\app\Controllers\cliente\Casos.php(24): view('cliente/casos/n...', Array)
#5 C:\xampp\htdocs\lexsoft\app\Controllers\cliente\Casos.php(19): App\Controllers\cliente\Casos->vistaDashboarCliente('casos/nuevoCaso', Array)
#6 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(936): App\Controllers\cliente\Casos->nuevo_caso()
#7 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\cliente\Casos))
#8 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\lexsoft\public\index.php(44): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2021-04-23 15:44:57 --> Function name must be a string
#0 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\View\View.php(220): include()
#1 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\View\View.php(222): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#2 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Common.php(1217): CodeIgniter\View\View->render('cliente/casos/n...', Array, true)
#3 C:\xampp\htdocs\lexsoft\app\Controllers\cliente\Casos.php(24): view('cliente/casos/n...', Array)
#4 C:\xampp\htdocs\lexsoft\app\Controllers\cliente\Casos.php(19): App\Controllers\cliente\Casos->vistaDashboarCliente('casos/nuevoCaso', Array)
#5 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(936): App\Controllers\cliente\Casos->nuevo_caso()
#6 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\cliente\Casos))
#7 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\lexsoft\public\index.php(44): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-04-23 15:45:10 --> Trying to get property 'id_user' of non-object
#0 C:\xampp\htdocs\lexsoft\app\Views\cliente\casos\nuevoCaso.php(25): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to get p...', 'C:\\xampp\\htdocs...', 25, Array)
#1 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\View\View.php(220): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\View\View.php(222): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Common.php(1217): CodeIgniter\View\View->render('cliente/casos/n...', Array, true)
#4 C:\xampp\htdocs\lexsoft\app\Controllers\cliente\Casos.php(24): view('cliente/casos/n...', Array)
#5 C:\xampp\htdocs\lexsoft\app\Controllers\cliente\Casos.php(19): App\Controllers\cliente\Casos->vistaDashboarCliente('casos/nuevoCaso', Array)
#6 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(936): App\Controllers\cliente\Casos->nuevo_caso()
#7 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\cliente\Casos))
#8 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\lexsoft\public\index.php(44): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2021-04-23 15:45:11 --> Trying to get property 'id_user' of non-object
#0 C:\xampp\htdocs\lexsoft\app\Views\cliente\casos\nuevoCaso.php(25): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to get p...', 'C:\\xampp\\htdocs...', 25, Array)
#1 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\View\View.php(220): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\View\View.php(222): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Common.php(1217): CodeIgniter\View\View->render('cliente/casos/n...', Array, true)
#4 C:\xampp\htdocs\lexsoft\app\Controllers\cliente\Casos.php(24): view('cliente/casos/n...', Array)
#5 C:\xampp\htdocs\lexsoft\app\Controllers\cliente\Casos.php(19): App\Controllers\cliente\Casos->vistaDashboarCliente('casos/nuevoCaso', Array)
#6 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(936): App\Controllers\cliente\Casos->nuevo_caso()
#7 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\cliente\Casos))
#8 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\lexsoft\public\index.php(44): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2021-04-23 15:45:11 --> Trying to get property 'id_user' of non-object
#0 C:\xampp\htdocs\lexsoft\app\Views\cliente\casos\nuevoCaso.php(25): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to get p...', 'C:\\xampp\\htdocs...', 25, Array)
#1 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\View\View.php(220): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\View\View.php(222): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Common.php(1217): CodeIgniter\View\View->render('cliente/casos/n...', Array, true)
#4 C:\xampp\htdocs\lexsoft\app\Controllers\cliente\Casos.php(24): view('cliente/casos/n...', Array)
#5 C:\xampp\htdocs\lexsoft\app\Controllers\cliente\Casos.php(19): App\Controllers\cliente\Casos->vistaDashboarCliente('casos/nuevoCaso', Array)
#6 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(936): App\Controllers\cliente\Casos->nuevo_caso()
#7 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\cliente\Casos))
#8 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\lexsoft\public\index.php(44): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2021-04-23 15:45:11 --> Trying to get property 'id_user' of non-object
#0 C:\xampp\htdocs\lexsoft\app\Views\cliente\casos\nuevoCaso.php(25): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to get p...', 'C:\\xampp\\htdocs...', 25, Array)
#1 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\View\View.php(220): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\View\View.php(222): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Common.php(1217): CodeIgniter\View\View->render('cliente/casos/n...', Array, true)
#4 C:\xampp\htdocs\lexsoft\app\Controllers\cliente\Casos.php(24): view('cliente/casos/n...', Array)
#5 C:\xampp\htdocs\lexsoft\app\Controllers\cliente\Casos.php(19): App\Controllers\cliente\Casos->vistaDashboarCliente('casos/nuevoCaso', Array)
#6 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(936): App\Controllers\cliente\Casos->nuevo_caso()
#7 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\cliente\Casos))
#8 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\lexsoft\public\index.php(44): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2021-04-23 15:45:11 --> Trying to get property 'id_user' of non-object
#0 C:\xampp\htdocs\lexsoft\app\Views\cliente\casos\nuevoCaso.php(25): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to get p...', 'C:\\xampp\\htdocs...', 25, Array)
#1 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\View\View.php(220): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\View\View.php(222): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Common.php(1217): CodeIgniter\View\View->render('cliente/casos/n...', Array, true)
#4 C:\xampp\htdocs\lexsoft\app\Controllers\cliente\Casos.php(24): view('cliente/casos/n...', Array)
#5 C:\xampp\htdocs\lexsoft\app\Controllers\cliente\Casos.php(19): App\Controllers\cliente\Casos->vistaDashboarCliente('casos/nuevoCaso', Array)
#6 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(936): App\Controllers\cliente\Casos->nuevo_caso()
#7 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\cliente\Casos))
#8 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\lexsoft\public\index.php(44): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2021-04-23 15:45:11 --> Trying to get property 'id_user' of non-object
#0 C:\xampp\htdocs\lexsoft\app\Views\cliente\casos\nuevoCaso.php(25): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to get p...', 'C:\\xampp\\htdocs...', 25, Array)
#1 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\View\View.php(220): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\View\View.php(222): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Common.php(1217): CodeIgniter\View\View->render('cliente/casos/n...', Array, true)
#4 C:\xampp\htdocs\lexsoft\app\Controllers\cliente\Casos.php(24): view('cliente/casos/n...', Array)
#5 C:\xampp\htdocs\lexsoft\app\Controllers\cliente\Casos.php(19): App\Controllers\cliente\Casos->vistaDashboarCliente('casos/nuevoCaso', Array)
#6 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(936): App\Controllers\cliente\Casos->nuevo_caso()
#7 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\cliente\Casos))
#8 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\lexsoft\public\index.php(44): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2021-04-23 15:45:12 --> Trying to get property 'id_user' of non-object
#0 C:\xampp\htdocs\lexsoft\app\Views\cliente\casos\nuevoCaso.php(25): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to get p...', 'C:\\xampp\\htdocs...', 25, Array)
#1 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\View\View.php(220): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\View\View.php(222): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Common.php(1217): CodeIgniter\View\View->render('cliente/casos/n...', Array, true)
#4 C:\xampp\htdocs\lexsoft\app\Controllers\cliente\Casos.php(24): view('cliente/casos/n...', Array)
#5 C:\xampp\htdocs\lexsoft\app\Controllers\cliente\Casos.php(19): App\Controllers\cliente\Casos->vistaDashboarCliente('casos/nuevoCaso', Array)
#6 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(936): App\Controllers\cliente\Casos->nuevo_caso()
#7 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\cliente\Casos))
#8 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\lexsoft\public\index.php(44): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2021-04-23 15:45:12 --> Trying to get property 'id_user' of non-object
#0 C:\xampp\htdocs\lexsoft\app\Views\cliente\casos\nuevoCaso.php(25): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to get p...', 'C:\\xampp\\htdocs...', 25, Array)
#1 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\View\View.php(220): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\View\View.php(222): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Common.php(1217): CodeIgniter\View\View->render('cliente/casos/n...', Array, true)
#4 C:\xampp\htdocs\lexsoft\app\Controllers\cliente\Casos.php(24): view('cliente/casos/n...', Array)
#5 C:\xampp\htdocs\lexsoft\app\Controllers\cliente\Casos.php(19): App\Controllers\cliente\Casos->vistaDashboarCliente('casos/nuevoCaso', Array)
#6 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(936): App\Controllers\cliente\Casos->nuevo_caso()
#7 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\cliente\Casos))
#8 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\lexsoft\public\index.php(44): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2021-04-23 15:48:31 --> Function name must be a string
#0 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\View\View.php(220): include()
#1 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\View\View.php(222): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#2 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Common.php(1217): CodeIgniter\View\View->render('cliente/casos/n...', Array, true)
#3 C:\xampp\htdocs\lexsoft\app\Controllers\cliente\Casos.php(24): view('cliente/casos/n...', Array)
#4 C:\xampp\htdocs\lexsoft\app\Controllers\cliente\Casos.php(19): App\Controllers\cliente\Casos->vistaDashboarCliente('casos/nuevoCaso', Array)
#5 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(936): App\Controllers\cliente\Casos->nuevo_caso()
#6 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\cliente\Casos))
#7 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\lexsoft\public\index.php(44): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-04-23 15:48:47 --> Function name must be a string
#0 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\View\View.php(220): include()
#1 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\View\View.php(222): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#2 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Common.php(1217): CodeIgniter\View\View->render('cliente/casos/n...', Array, true)
#3 C:\xampp\htdocs\lexsoft\app\Controllers\cliente\Casos.php(24): view('cliente/casos/n...', Array)
#4 C:\xampp\htdocs\lexsoft\app\Controllers\cliente\Casos.php(19): App\Controllers\cliente\Casos->vistaDashboarCliente('casos/nuevoCaso', Array)
#5 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(936): App\Controllers\cliente\Casos->nuevo_caso()
#6 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\cliente\Casos))
#7 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\lexsoft\public\index.php(44): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-04-23 15:48:48 --> Function name must be a string
#0 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\View\View.php(220): include()
#1 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\View\View.php(222): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#2 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Common.php(1217): CodeIgniter\View\View->render('cliente/casos/n...', Array, true)
#3 C:\xampp\htdocs\lexsoft\app\Controllers\cliente\Casos.php(24): view('cliente/casos/n...', Array)
#4 C:\xampp\htdocs\lexsoft\app\Controllers\cliente\Casos.php(19): App\Controllers\cliente\Casos->vistaDashboarCliente('casos/nuevoCaso', Array)
#5 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(936): App\Controllers\cliente\Casos->nuevo_caso()
#6 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\cliente\Casos))
#7 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\lexsoft\public\index.php(44): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-04-23 15:48:48 --> Function name must be a string
#0 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\View\View.php(220): include()
#1 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\View\View.php(222): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#2 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Common.php(1217): CodeIgniter\View\View->render('cliente/casos/n...', Array, true)
#3 C:\xampp\htdocs\lexsoft\app\Controllers\cliente\Casos.php(24): view('cliente/casos/n...', Array)
#4 C:\xampp\htdocs\lexsoft\app\Controllers\cliente\Casos.php(19): App\Controllers\cliente\Casos->vistaDashboarCliente('casos/nuevoCaso', Array)
#5 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(936): App\Controllers\cliente\Casos->nuevo_caso()
#6 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\cliente\Casos))
#7 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\lexsoft\public\index.php(44): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-04-23 15:48:48 --> Function name must be a string
#0 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\View\View.php(220): include()
#1 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\View\View.php(222): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#2 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Common.php(1217): CodeIgniter\View\View->render('cliente/casos/n...', Array, true)
#3 C:\xampp\htdocs\lexsoft\app\Controllers\cliente\Casos.php(24): view('cliente/casos/n...', Array)
#4 C:\xampp\htdocs\lexsoft\app\Controllers\cliente\Casos.php(19): App\Controllers\cliente\Casos->vistaDashboarCliente('casos/nuevoCaso', Array)
#5 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(936): App\Controllers\cliente\Casos->nuevo_caso()
#6 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\cliente\Casos))
#7 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\lexsoft\public\index.php(44): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-04-23 15:48:48 --> Function name must be a string
#0 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\View\View.php(220): include()
#1 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\View\View.php(222): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#2 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Common.php(1217): CodeIgniter\View\View->render('cliente/casos/n...', Array, true)
#3 C:\xampp\htdocs\lexsoft\app\Controllers\cliente\Casos.php(24): view('cliente/casos/n...', Array)
#4 C:\xampp\htdocs\lexsoft\app\Controllers\cliente\Casos.php(19): App\Controllers\cliente\Casos->vistaDashboarCliente('casos/nuevoCaso', Array)
#5 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(936): App\Controllers\cliente\Casos->nuevo_caso()
#6 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\cliente\Casos))
#7 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\lexsoft\public\index.php(44): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-04-23 15:48:48 --> Function name must be a string
#0 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\View\View.php(220): include()
#1 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\View\View.php(222): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#2 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Common.php(1217): CodeIgniter\View\View->render('cliente/casos/n...', Array, true)
#3 C:\xampp\htdocs\lexsoft\app\Controllers\cliente\Casos.php(24): view('cliente/casos/n...', Array)
#4 C:\xampp\htdocs\lexsoft\app\Controllers\cliente\Casos.php(19): App\Controllers\cliente\Casos->vistaDashboarCliente('casos/nuevoCaso', Array)
#5 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(936): App\Controllers\cliente\Casos->nuevo_caso()
#6 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\cliente\Casos))
#7 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\lexsoft\public\index.php(44): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-04-23 15:49:04 --> Function name must be a string
#0 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\View\View.php(220): include()
#1 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\View\View.php(222): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#2 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Common.php(1217): CodeIgniter\View\View->render('cliente/casos/n...', Array, true)
#3 C:\xampp\htdocs\lexsoft\app\Controllers\cliente\Casos.php(24): view('cliente/casos/n...', Array)
#4 C:\xampp\htdocs\lexsoft\app\Controllers\cliente\Casos.php(19): App\Controllers\cliente\Casos->vistaDashboarCliente('casos/nuevoCaso', Array)
#5 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(936): App\Controllers\cliente\Casos->nuevo_caso()
#6 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\cliente\Casos))
#7 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\lexsoft\public\index.php(44): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-04-23 15:49:08 --> Function name must be a string
#0 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\View\View.php(220): include()
#1 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\View\View.php(222): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#2 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Common.php(1217): CodeIgniter\View\View->render('cliente/casos/n...', Array, true)
#3 C:\xampp\htdocs\lexsoft\app\Controllers\cliente\Casos.php(24): view('cliente/casos/n...', Array)
#4 C:\xampp\htdocs\lexsoft\app\Controllers\cliente\Casos.php(19): App\Controllers\cliente\Casos->vistaDashboarCliente('casos/nuevoCaso', Array)
#5 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(936): App\Controllers\cliente\Casos->nuevo_caso()
#6 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\cliente\Casos))
#7 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\lexsoft\public\index.php(44): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-04-23 15:49:08 --> Function name must be a string
#0 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\View\View.php(220): include()
#1 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\View\View.php(222): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#2 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Common.php(1217): CodeIgniter\View\View->render('cliente/casos/n...', Array, true)
#3 C:\xampp\htdocs\lexsoft\app\Controllers\cliente\Casos.php(24): view('cliente/casos/n...', Array)
#4 C:\xampp\htdocs\lexsoft\app\Controllers\cliente\Casos.php(19): App\Controllers\cliente\Casos->vistaDashboarCliente('casos/nuevoCaso', Array)
#5 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(936): App\Controllers\cliente\Casos->nuevo_caso()
#6 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\cliente\Casos))
#7 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\lexsoft\public\index.php(44): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-04-23 15:49:08 --> Function name must be a string
#0 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\View\View.php(220): include()
#1 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\View\View.php(222): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#2 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Common.php(1217): CodeIgniter\View\View->render('cliente/casos/n...', Array, true)
#3 C:\xampp\htdocs\lexsoft\app\Controllers\cliente\Casos.php(24): view('cliente/casos/n...', Array)
#4 C:\xampp\htdocs\lexsoft\app\Controllers\cliente\Casos.php(19): App\Controllers\cliente\Casos->vistaDashboarCliente('casos/nuevoCaso', Array)
#5 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(936): App\Controllers\cliente\Casos->nuevo_caso()
#6 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\cliente\Casos))
#7 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\lexsoft\public\index.php(44): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-04-23 15:49:09 --> Function name must be a string
#0 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\View\View.php(220): include()
#1 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\View\View.php(222): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#2 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Common.php(1217): CodeIgniter\View\View->render('cliente/casos/n...', Array, true)
#3 C:\xampp\htdocs\lexsoft\app\Controllers\cliente\Casos.php(24): view('cliente/casos/n...', Array)
#4 C:\xampp\htdocs\lexsoft\app\Controllers\cliente\Casos.php(19): App\Controllers\cliente\Casos->vistaDashboarCliente('casos/nuevoCaso', Array)
#5 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(936): App\Controllers\cliente\Casos->nuevo_caso()
#6 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\cliente\Casos))
#7 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\lexsoft\public\index.php(44): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-04-23 15:49:09 --> Function name must be a string
#0 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\View\View.php(220): include()
#1 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\View\View.php(222): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#2 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Common.php(1217): CodeIgniter\View\View->render('cliente/casos/n...', Array, true)
#3 C:\xampp\htdocs\lexsoft\app\Controllers\cliente\Casos.php(24): view('cliente/casos/n...', Array)
#4 C:\xampp\htdocs\lexsoft\app\Controllers\cliente\Casos.php(19): App\Controllers\cliente\Casos->vistaDashboarCliente('casos/nuevoCaso', Array)
#5 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(936): App\Controllers\cliente\Casos->nuevo_caso()
#6 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\cliente\Casos))
#7 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\lexsoft\public\index.php(44): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-04-23 15:49:09 --> Function name must be a string
#0 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\View\View.php(220): include()
#1 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\View\View.php(222): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#2 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Common.php(1217): CodeIgniter\View\View->render('cliente/casos/n...', Array, true)
#3 C:\xampp\htdocs\lexsoft\app\Controllers\cliente\Casos.php(24): view('cliente/casos/n...', Array)
#4 C:\xampp\htdocs\lexsoft\app\Controllers\cliente\Casos.php(19): App\Controllers\cliente\Casos->vistaDashboarCliente('casos/nuevoCaso', Array)
#5 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(936): App\Controllers\cliente\Casos->nuevo_caso()
#6 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\cliente\Casos))
#7 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\lexsoft\public\index.php(44): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-04-23 15:49:09 --> Function name must be a string
#0 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\View\View.php(220): include()
#1 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\View\View.php(222): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#2 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Common.php(1217): CodeIgniter\View\View->render('cliente/casos/n...', Array, true)
#3 C:\xampp\htdocs\lexsoft\app\Controllers\cliente\Casos.php(24): view('cliente/casos/n...', Array)
#4 C:\xampp\htdocs\lexsoft\app\Controllers\cliente\Casos.php(19): App\Controllers\cliente\Casos->vistaDashboarCliente('casos/nuevoCaso', Array)
#5 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(936): App\Controllers\cliente\Casos->nuevo_caso()
#6 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\cliente\Casos))
#7 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\lexsoft\public\index.php(44): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-04-23 15:49:09 --> Function name must be a string
#0 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\View\View.php(220): include()
#1 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\View\View.php(222): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#2 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Common.php(1217): CodeIgniter\View\View->render('cliente/casos/n...', Array, true)
#3 C:\xampp\htdocs\lexsoft\app\Controllers\cliente\Casos.php(24): view('cliente/casos/n...', Array)
#4 C:\xampp\htdocs\lexsoft\app\Controllers\cliente\Casos.php(19): App\Controllers\cliente\Casos->vistaDashboarCliente('casos/nuevoCaso', Array)
#5 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(936): App\Controllers\cliente\Casos->nuevo_caso()
#6 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\cliente\Casos))
#7 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\lexsoft\public\index.php(44): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-04-23 15:49:10 --> Function name must be a string
#0 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\View\View.php(220): include()
#1 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\View\View.php(222): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#2 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Common.php(1217): CodeIgniter\View\View->render('cliente/casos/n...', Array, true)
#3 C:\xampp\htdocs\lexsoft\app\Controllers\cliente\Casos.php(24): view('cliente/casos/n...', Array)
#4 C:\xampp\htdocs\lexsoft\app\Controllers\cliente\Casos.php(19): App\Controllers\cliente\Casos->vistaDashboarCliente('casos/nuevoCaso', Array)
#5 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(936): App\Controllers\cliente\Casos->nuevo_caso()
#6 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\cliente\Casos))
#7 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\lexsoft\public\index.php(44): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-04-23 15:50:13 --> Trying to get property 'id_creado' of non-object
#0 C:\xampp\htdocs\lexsoft\app\Views\cliente\casos\nuevoCaso.php(28): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to get p...', 'C:\\xampp\\htdocs...', 28, Array)
#1 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\View\View.php(220): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\View\View.php(222): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Common.php(1217): CodeIgniter\View\View->render('cliente/casos/n...', Array, true)
#4 C:\xampp\htdocs\lexsoft\app\Controllers\cliente\Casos.php(24): view('cliente/casos/n...', Array)
#5 C:\xampp\htdocs\lexsoft\app\Controllers\cliente\Casos.php(19): App\Controllers\cliente\Casos->vistaDashboarCliente('casos/nuevoCaso', Array)
#6 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(936): App\Controllers\cliente\Casos->nuevo_caso()
#7 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\cliente\Casos))
#8 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\lexsoft\public\index.php(44): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2021-04-23 15:50:33 --> Trying to get property 'id_user' of non-object
#0 C:\xampp\htdocs\lexsoft\app\Views\cliente\casos\nuevoCaso.php(28): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to get p...', 'C:\\xampp\\htdocs...', 28, Array)
#1 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\View\View.php(220): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\View\View.php(222): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Common.php(1217): CodeIgniter\View\View->render('cliente/casos/n...', Array, true)
#4 C:\xampp\htdocs\lexsoft\app\Controllers\cliente\Casos.php(24): view('cliente/casos/n...', Array)
#5 C:\xampp\htdocs\lexsoft\app\Controllers\cliente\Casos.php(19): App\Controllers\cliente\Casos->vistaDashboarCliente('casos/nuevoCaso', Array)
#6 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(936): App\Controllers\cliente\Casos->nuevo_caso()
#7 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\cliente\Casos))
#8 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\lexsoft\public\index.php(44): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2021-04-23 15:50:34 --> Trying to get property 'id_user' of non-object
#0 C:\xampp\htdocs\lexsoft\app\Views\cliente\casos\nuevoCaso.php(28): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to get p...', 'C:\\xampp\\htdocs...', 28, Array)
#1 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\View\View.php(220): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\View\View.php(222): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Common.php(1217): CodeIgniter\View\View->render('cliente/casos/n...', Array, true)
#4 C:\xampp\htdocs\lexsoft\app\Controllers\cliente\Casos.php(24): view('cliente/casos/n...', Array)
#5 C:\xampp\htdocs\lexsoft\app\Controllers\cliente\Casos.php(19): App\Controllers\cliente\Casos->vistaDashboarCliente('casos/nuevoCaso', Array)
#6 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(936): App\Controllers\cliente\Casos->nuevo_caso()
#7 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\cliente\Casos))
#8 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\lexsoft\public\index.php(44): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2021-04-23 15:50:34 --> Trying to get property 'id_user' of non-object
#0 C:\xampp\htdocs\lexsoft\app\Views\cliente\casos\nuevoCaso.php(28): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to get p...', 'C:\\xampp\\htdocs...', 28, Array)
#1 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\View\View.php(220): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\View\View.php(222): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Common.php(1217): CodeIgniter\View\View->render('cliente/casos/n...', Array, true)
#4 C:\xampp\htdocs\lexsoft\app\Controllers\cliente\Casos.php(24): view('cliente/casos/n...', Array)
#5 C:\xampp\htdocs\lexsoft\app\Controllers\cliente\Casos.php(19): App\Controllers\cliente\Casos->vistaDashboarCliente('casos/nuevoCaso', Array)
#6 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(936): App\Controllers\cliente\Casos->nuevo_caso()
#7 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\cliente\Casos))
#8 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\lexsoft\public\index.php(44): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2021-04-23 15:50:34 --> Trying to get property 'id_user' of non-object
#0 C:\xampp\htdocs\lexsoft\app\Views\cliente\casos\nuevoCaso.php(28): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to get p...', 'C:\\xampp\\htdocs...', 28, Array)
#1 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\View\View.php(220): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\View\View.php(222): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Common.php(1217): CodeIgniter\View\View->render('cliente/casos/n...', Array, true)
#4 C:\xampp\htdocs\lexsoft\app\Controllers\cliente\Casos.php(24): view('cliente/casos/n...', Array)
#5 C:\xampp\htdocs\lexsoft\app\Controllers\cliente\Casos.php(19): App\Controllers\cliente\Casos->vistaDashboarCliente('casos/nuevoCaso', Array)
#6 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(936): App\Controllers\cliente\Casos->nuevo_caso()
#7 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\cliente\Casos))
#8 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\lexsoft\public\index.php(44): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2021-04-23 15:50:35 --> Trying to get property 'id_user' of non-object
#0 C:\xampp\htdocs\lexsoft\app\Views\cliente\casos\nuevoCaso.php(28): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to get p...', 'C:\\xampp\\htdocs...', 28, Array)
#1 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\View\View.php(220): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\View\View.php(222): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Common.php(1217): CodeIgniter\View\View->render('cliente/casos/n...', Array, true)
#4 C:\xampp\htdocs\lexsoft\app\Controllers\cliente\Casos.php(24): view('cliente/casos/n...', Array)
#5 C:\xampp\htdocs\lexsoft\app\Controllers\cliente\Casos.php(19): App\Controllers\cliente\Casos->vistaDashboarCliente('casos/nuevoCaso', Array)
#6 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(936): App\Controllers\cliente\Casos->nuevo_caso()
#7 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\cliente\Casos))
#8 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\lexsoft\public\index.php(44): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2021-04-23 16:03:55 --> There is no data to insert.
#0 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\BaseModel.php(735): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('insert')
#1 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Model.php(705): CodeIgniter\BaseModel->insert(Array, true)
#2 C:\xampp\htdocs\lexsoft\app\Controllers\cliente\Casos.php(72): CodeIgniter\Model->insert(Array)
#3 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(936): App\Controllers\cliente\Casos->insert_caso()
#4 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\cliente\Casos))
#5 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\lexsoft\public\index.php(44): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2021-04-23 16:05:18 --> Class 'App\Models\CasoModal' not found
#0 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(936): App\Controllers\cliente\Casos->insert_caso()
#1 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\cliente\Casos))
#2 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\lexsoft\public\index.php(44): CodeIgniter\CodeIgniter->run()
#4 {main}
ERROR - 2021-04-23 16:06:03 --> mysqli_sql_exception: Column 'doc_caso' cannot be null in C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:314
Stack trace:
#0 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(314): mysqli->query('INSERT INTO `le...')
#1 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Database\BaseConnection.php(713): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `le...')
#2 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Database\BaseConnection.php(641): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `le...')
#3 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2263): CodeIgniter\Database\BaseConnection->query('INSERT INTO `le...', Array, false)
#4 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Model.php(278): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\BaseModel.php(758): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Model.php(705): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\lexsoft\app\Controllers\cliente\Casos.php(74): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(936): App\Controllers\cliente\Casos->insert_caso()
#9 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\cliente\Casos))
#10 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\lexsoft\public\index.php(44): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2021-04-23 16:06:03 --> Column 'doc_caso' cannot be null
#0 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(314): mysqli->query('INSERT INTO `le...')
#1 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Database\BaseConnection.php(713): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `le...')
#2 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Database\BaseConnection.php(641): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `le...')
#3 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2263): CodeIgniter\Database\BaseConnection->query('INSERT INTO `le...', Array, false)
#4 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Model.php(278): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\BaseModel.php(758): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Model.php(705): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\lexsoft\app\Controllers\cliente\Casos.php(74): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(936): App\Controllers\cliente\Casos->insert_caso()
#9 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\cliente\Casos))
#10 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\lexsoft\public\index.php(44): CodeIgniter\CodeIgniter->run()
#12 {main}
ERROR - 2021-04-23 16:06:39 --> mysqli_sql_exception: Column 'doc_caso' cannot be null in C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:314
Stack trace:
#0 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(314): mysqli->query('INSERT INTO `le...')
#1 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Database\BaseConnection.php(713): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `le...')
#2 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Database\BaseConnection.php(641): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `le...')
#3 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2263): CodeIgniter\Database\BaseConnection->query('INSERT INTO `le...', Array, false)
#4 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Model.php(278): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\BaseModel.php(758): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Model.php(705): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\lexsoft\app\Controllers\cliente\Casos.php(74): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(936): App\Controllers\cliente\Casos->insert_caso()
#9 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\cliente\Casos))
#10 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\lexsoft\public\index.php(44): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2021-04-23 16:06:39 --> Column 'doc_caso' cannot be null
#0 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(314): mysqli->query('INSERT INTO `le...')
#1 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Database\BaseConnection.php(713): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `le...')
#2 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Database\BaseConnection.php(641): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `le...')
#3 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2263): CodeIgniter\Database\BaseConnection->query('INSERT INTO `le...', Array, false)
#4 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Model.php(278): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\BaseModel.php(758): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Model.php(705): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\lexsoft\app\Controllers\cliente\Casos.php(74): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(936): App\Controllers\cliente\Casos->insert_caso()
#9 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\cliente\Casos))
#10 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\lexsoft\public\index.php(44): CodeIgniter\CodeIgniter->run()
#12 {main}
ERROR - 2021-04-23 16:06:52 --> mysqli_sql_exception: Column 'estado' cannot be null in C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:314
Stack trace:
#0 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(314): mysqli->query('INSERT INTO `le...')
#1 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Database\BaseConnection.php(713): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `le...')
#2 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Database\BaseConnection.php(641): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `le...')
#3 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2263): CodeIgniter\Database\BaseConnection->query('INSERT INTO `le...', Array, false)
#4 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Model.php(278): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\BaseModel.php(758): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Model.php(705): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\lexsoft\app\Controllers\cliente\Casos.php(74): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(936): App\Controllers\cliente\Casos->insert_caso()
#9 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\cliente\Casos))
#10 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\lexsoft\public\index.php(44): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2021-04-23 16:06:52 --> Column 'estado' cannot be null
#0 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(314): mysqli->query('INSERT INTO `le...')
#1 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Database\BaseConnection.php(713): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `le...')
#2 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Database\BaseConnection.php(641): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `le...')
#3 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2263): CodeIgniter\Database\BaseConnection->query('INSERT INTO `le...', Array, false)
#4 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Model.php(278): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\BaseModel.php(758): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Model.php(705): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\lexsoft\app\Controllers\cliente\Casos.php(74): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(936): App\Controllers\cliente\Casos->insert_caso()
#9 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\cliente\Casos))
#10 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\lexsoft\public\index.php(44): CodeIgniter\CodeIgniter->run()
#12 {main}
ERROR - 2021-04-23 16:11:02 --> mysqli_sql_exception: Column 'estado' cannot be null in C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:314
Stack trace:
#0 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(314): mysqli->query('INSERT INTO `le...')
#1 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Database\BaseConnection.php(713): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `le...')
#2 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Database\BaseConnection.php(641): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `le...')
#3 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2263): CodeIgniter\Database\BaseConnection->query('INSERT INTO `le...', Array, false)
#4 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Model.php(278): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\BaseModel.php(758): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Model.php(705): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\lexsoft\app\Controllers\cliente\Casos.php(74): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(936): App\Controllers\cliente\Casos->insert_caso()
#9 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\cliente\Casos))
#10 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\lexsoft\public\index.php(44): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2021-04-23 16:11:02 --> Column 'estado' cannot be null
#0 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(314): mysqli->query('INSERT INTO `le...')
#1 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Database\BaseConnection.php(713): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `le...')
#2 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Database\BaseConnection.php(641): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `le...')
#3 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2263): CodeIgniter\Database\BaseConnection->query('INSERT INTO `le...', Array, false)
#4 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Model.php(278): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\BaseModel.php(758): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Model.php(705): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\lexsoft\app\Controllers\cliente\Casos.php(74): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(936): App\Controllers\cliente\Casos->insert_caso()
#9 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\cliente\Casos))
#10 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\lexsoft\public\index.php(44): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2021-04-23 16:29:47 --> Trying to access array offset on value of type null
#0 C:\xampp\htdocs\lexsoft\app\Views\admin\usuario\editUser.php(19): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to acces...', 'C:\\xampp\\htdocs...', 19, Array)
#1 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\View\View.php(220): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\View\View.php(222): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Common.php(1217): CodeIgniter\View\View->render('admin/usuario/e...', Array, true)
#4 C:\xampp\htdocs\lexsoft\app\Controllers\admin\User.php(135): view('admin/usuario/e...', Array)
#5 C:\xampp\htdocs\lexsoft\app\Controllers\admin\User.php(88): App\Controllers\admin\User->vistaDashboarAdmin('usuario/editUse...', Array)
#6 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(936): App\Controllers\admin\User->editUser('dist', 'img', 'user1-128x128.j...')
#7 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\admin\User))
#8 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\lexsoft\public\index.php(44): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2021-04-23 16:29:47 --> Trying to access array offset on value of type null
#0 C:\xampp\htdocs\lexsoft\app\Views\admin\usuario\editUser.php(19): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to acces...', 'C:\\xampp\\htdocs...', 19, Array)
#1 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\View\View.php(220): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\View\View.php(222): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Common.php(1217): CodeIgniter\View\View->render('admin/usuario/e...', Array, true)
#4 C:\xampp\htdocs\lexsoft\app\Controllers\admin\User.php(135): view('admin/usuario/e...', Array)
#5 C:\xampp\htdocs\lexsoft\app\Controllers\admin\User.php(88): App\Controllers\admin\User->vistaDashboarAdmin('usuario/editUse...', Array)
#6 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(936): App\Controllers\admin\User->editUser('dist', 'img', 'user8-128x128.j...')
#7 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\admin\User))
#8 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\lexsoft\public\index.php(44): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2021-04-23 16:29:47 --> Trying to access array offset on value of type null
#0 C:\xampp\htdocs\lexsoft\app\Views\admin\usuario\editUser.php(19): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to acces...', 'C:\\xampp\\htdocs...', 19, Array)
#1 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\View\View.php(220): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\View\View.php(222): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Common.php(1217): CodeIgniter\View\View->render('admin/usuario/e...', Array, true)
#4 C:\xampp\htdocs\lexsoft\app\Controllers\admin\User.php(135): view('admin/usuario/e...', Array)
#5 C:\xampp\htdocs\lexsoft\app\Controllers\admin\User.php(88): App\Controllers\admin\User->vistaDashboarAdmin('usuario/editUse...', Array)
#6 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(936): App\Controllers\admin\User->editUser('dist', 'img', 'user3-128x128.j...')
#7 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\admin\User))
#8 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\lexsoft\public\index.php(44): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2021-04-23 16:34:30 --> Trying to access array offset on value of type null
#0 C:\xampp\htdocs\lexsoft\app\Views\cliente\usuarioCliente\editCliente.php(19): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to acces...', 'C:\\xampp\\htdocs...', 19, Array)
#1 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\View\View.php(220): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\View\View.php(222): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Common.php(1217): CodeIgniter\View\View->render('cliente/usuario...', Array, true)
#4 C:\xampp\htdocs\lexsoft\app\Controllers\cliente\UserCliente.php(136): view('cliente/usuario...', Array)
#5 C:\xampp\htdocs\lexsoft\app\Controllers\cliente\UserCliente.php(89): App\Controllers\cliente\UserCliente->vistaDashboarCliente('usuarioCliente/...', Array)
#6 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(936): App\Controllers\cliente\UserCliente->edit_cliente('dist', 'img', 'user1-128x128.j...')
#7 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\cliente\UserCliente))
#8 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\lexsoft\public\index.php(44): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2021-04-23 16:34:30 --> Trying to access array offset on value of type null
#0 C:\xampp\htdocs\lexsoft\app\Views\cliente\usuarioCliente\editCliente.php(19): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to acces...', 'C:\\xampp\\htdocs...', 19, Array)
#1 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\View\View.php(220): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\View\View.php(222): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Common.php(1217): CodeIgniter\View\View->render('cliente/usuario...', Array, true)
#4 C:\xampp\htdocs\lexsoft\app\Controllers\cliente\UserCliente.php(136): view('cliente/usuario...', Array)
#5 C:\xampp\htdocs\lexsoft\app\Controllers\cliente\UserCliente.php(89): App\Controllers\cliente\UserCliente->vistaDashboarCliente('usuarioCliente/...', Array)
#6 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(936): App\Controllers\cliente\UserCliente->edit_cliente('dist', 'img', 'user8-128x128.j...')
#7 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\cliente\UserCliente))
#8 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\lexsoft\public\index.php(44): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2021-04-23 16:34:30 --> Trying to access array offset on value of type null
#0 C:\xampp\htdocs\lexsoft\app\Views\cliente\usuarioCliente\editCliente.php(19): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to acces...', 'C:\\xampp\\htdocs...', 19, Array)
#1 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\View\View.php(220): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\View\View.php(222): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Common.php(1217): CodeIgniter\View\View->render('cliente/usuario...', Array, true)
#4 C:\xampp\htdocs\lexsoft\app\Controllers\cliente\UserCliente.php(136): view('cliente/usuario...', Array)
#5 C:\xampp\htdocs\lexsoft\app\Controllers\cliente\UserCliente.php(89): App\Controllers\cliente\UserCliente->vistaDashboarCliente('usuarioCliente/...', Array)
#6 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(936): App\Controllers\cliente\UserCliente->edit_cliente('dist', 'img', 'user3-128x128.j...')
#7 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\cliente\UserCliente))
#8 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\lexsoft\public\index.php(44): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2021-04-23 16:35:23 --> Trying to access array offset on value of type null
#0 C:\xampp\htdocs\lexsoft\app\Views\admin\usuario\editUser.php(19): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to acces...', 'C:\\xampp\\htdocs...', 19, Array)
#1 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\View\View.php(220): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\View\View.php(222): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Common.php(1217): CodeIgniter\View\View->render('admin/usuario/e...', Array, true)
#4 C:\xampp\htdocs\lexsoft\app\Controllers\admin\User.php(135): view('admin/usuario/e...', Array)
#5 C:\xampp\htdocs\lexsoft\app\Controllers\admin\User.php(88): App\Controllers\admin\User->vistaDashboarAdmin('usuario/editUse...', Array)
#6 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(936): App\Controllers\admin\User->editUser('dist', 'img', 'user1-128x128.j...')
#7 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\admin\User))
#8 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\lexsoft\public\index.php(44): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2021-04-23 16:35:23 --> Trying to access array offset on value of type null
#0 C:\xampp\htdocs\lexsoft\app\Views\admin\usuario\editUser.php(19): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to acces...', 'C:\\xampp\\htdocs...', 19, Array)
#1 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\View\View.php(220): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\View\View.php(222): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Common.php(1217): CodeIgniter\View\View->render('admin/usuario/e...', Array, true)
#4 C:\xampp\htdocs\lexsoft\app\Controllers\admin\User.php(135): view('admin/usuario/e...', Array)
#5 C:\xampp\htdocs\lexsoft\app\Controllers\admin\User.php(88): App\Controllers\admin\User->vistaDashboarAdmin('usuario/editUse...', Array)
#6 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(936): App\Controllers\admin\User->editUser('dist', 'img', 'user8-128x128.j...')
#7 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\admin\User))
#8 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\lexsoft\public\index.php(44): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2021-04-23 16:35:23 --> Trying to access array offset on value of type null
#0 C:\xampp\htdocs\lexsoft\app\Views\admin\usuario\editUser.php(19): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to acces...', 'C:\\xampp\\htdocs...', 19, Array)
#1 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\View\View.php(220): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\View\View.php(222): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\Common.php(1217): CodeIgniter\View\View->render('admin/usuario/e...', Array, true)
#4 C:\xampp\htdocs\lexsoft\app\Controllers\admin\User.php(135): view('admin/usuario/e...', Array)
#5 C:\xampp\htdocs\lexsoft\app\Controllers\admin\User.php(88): App\Controllers\admin\User->vistaDashboarAdmin('usuario/editUse...', Array)
#6 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(936): App\Controllers\admin\User->editUser('dist', 'img', 'user3-128x128.j...')
#7 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\admin\User))
#8 C:\xampp\htdocs\lexsoft\vendor\codeigniter4\framework\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\lexsoft\public\index.php(44): CodeIgniter\CodeIgniter->run()
#10 {main}
